name: Publish qwc-uwsgi-base docker image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *" # every Tuesday on 6:00 UTC

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          SHOULD_RUN=true
          tag=$(date +"v%Y.%m.%d")
          echo "DEBUG: tag=$tag"
          echo "DEBUG: Lokale Tags vor Fetch:"
          git tag
          echo "DEBUG: Remote Tags:"
          git ls-remote --tags origin
          # Test: funktioniert 'git tag --list'?
          echo "DEBUG: git tag --list '$tag'"
          git tag --list "$tag"

          if git tag --list "$tag" | grep -q .; then
            echo "DEBUG: Tag $tag existiert lokal"
          else
            echo "DEBUG: Tag $tag existiert NICHT lokal"
          fi
          # if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF" == refs/tags/* ]]; then
          #   echo "alpine_tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          #   echo "ubuntu_tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          # elif [[ "$GITHUB_EVENT_NAME" == "schedule" ]]; then
          #   echo "$(git tag --list "$tag")"
          #   if git tag --list "$tag" | grep -q .; then
          #     echo "Tag $tag already exists â€“ skipping."
          #   else
          #     git tag "$tag"
          #     git push origin "$tag"
          #     echo "Tag $tag created and pushed."
          #     echo "alpine_tag=$tag" >>$GITHUB_OUTPUT
          #     echo "ubuntu_tag=$tag" >>$GITHUB_OUTPUT
          #   fi
          # else
          #   SHOULD_RUN=false
          # fi
          # echo "run_next=$SHOULD_RUN" >> "$GITHUB_OUTPUT"
          
      - name: Print tags
        id: print_tag
        run: |
          echo "Alpine tag: ${{ steps.get_tag.outputs.alpine_tag }}"
          echo "Ubuntu tag: ${{ steps.get_tag.outputs.ubuntu_tag }}"

      - name: Set up QEMU
        if: steps.get_tag.outputs.run_next == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: steps.get_tag.outputs.run_next == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build and publish Alpine docker image
      #    if: steps.get_tag.outputs.run_next == 'true'
      #   uses: elgohr/Publish-Docker-Github-Action@v4
      #   with:
      #     name: sourcepole/qwc-uwsgi-base
      #     username: ${{ secrets.DOCKER_HUB_USER }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     tags: "${{ steps.get_tag.outputs.alpine_tag }},alpine-${{ steps.get_tag.outputs.alpine_tag }}"
      #     workdir: alpine
      #     platforms: linux/arm64,linux/amd64

      # - name: Build and publish Ubuntu docker image
      #   if: steps.get_tag.outputs.run_next == 'true'
      #   uses: elgohr/Publish-Docker-Github-Action@v4
      #   with:
      #     name: sourcepole/qwc-uwsgi-base
      #     username: ${{ secrets.DOCKER_HUB_USER }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     tags: "ubuntu-${{ steps.get_tag.outputs.ubuntu_tag }}"
      #     workdir: ubuntu
      #     platforms: linux/arm64,linux/amd64
